default:
  paths:
    features: ../../features
  extensions:
    Behat\MinkExtension\Extension:
      base_url:  'http://test.localhost:8888/bdd/'
      goutte:    ~
      selenium: ~
      javascript_session: selenium
